sudo: required
services: 
 - docker

before_install:
 - docker build -t distantgabe/docker-react -f Dockerfile.dev .

script:
 - docker run distantgabe/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "sa-east-1"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-sa-east-1-520652442850"
 bucket_path "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SERCRET_KEY"
